//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilPrice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pttor.com", ConfigurationName="OilPrice.OilPriceSoap")]
    public interface OilPriceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pttor.com/CurrentOilPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<OilPrice.CurrentOilPriceResponse> CurrentOilPriceAsync(OilPrice.CurrentOilPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pttor.com/CurrentOilPriceProvincial", ReplyAction="*")]
        System.Threading.Tasks.Task<OilPrice.CurrentOilPriceProvincialResponse> CurrentOilPriceProvincialAsync(OilPrice.CurrentOilPriceProvincialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pttor.com/GetOilPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<OilPrice.GetOilPriceResponse> GetOilPriceAsync(OilPrice.GetOilPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pttor.com/GetOilPriceProvincial", ReplyAction="*")]
        System.Threading.Tasks.Task<OilPrice.GetOilPriceProvincialResponse> GetOilPriceProvincialAsync(OilPrice.GetOilPriceProvincialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentOilPriceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentOilPrice", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.CurrentOilPriceRequestBody Body;
        
        public CurrentOilPriceRequest()
        {
        }
        
        public CurrentOilPriceRequest(OilPrice.CurrentOilPriceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class CurrentOilPriceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Language;
        
        public CurrentOilPriceRequestBody()
        {
        }
        
        public CurrentOilPriceRequestBody(string Language)
        {
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentOilPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentOilPriceResponse", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.CurrentOilPriceResponseBody Body;
        
        public CurrentOilPriceResponse()
        {
        }
        
        public CurrentOilPriceResponse(OilPrice.CurrentOilPriceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class CurrentOilPriceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentOilPriceResult;
        
        public CurrentOilPriceResponseBody()
        {
        }
        
        public CurrentOilPriceResponseBody(string CurrentOilPriceResult)
        {
            this.CurrentOilPriceResult = CurrentOilPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentOilPriceProvincialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentOilPriceProvincial", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.CurrentOilPriceProvincialRequestBody Body;
        
        public CurrentOilPriceProvincialRequest()
        {
        }
        
        public CurrentOilPriceProvincialRequest(OilPrice.CurrentOilPriceProvincialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class CurrentOilPriceProvincialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Language;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Province;
        
        public CurrentOilPriceProvincialRequestBody()
        {
        }
        
        public CurrentOilPriceProvincialRequestBody(string Language, string Province)
        {
            this.Language = Language;
            this.Province = Province;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentOilPriceProvincialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentOilPriceProvincialResponse", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.CurrentOilPriceProvincialResponseBody Body;
        
        public CurrentOilPriceProvincialResponse()
        {
        }
        
        public CurrentOilPriceProvincialResponse(OilPrice.CurrentOilPriceProvincialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class CurrentOilPriceProvincialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentOilPriceProvincialResult;
        
        public CurrentOilPriceProvincialResponseBody()
        {
        }
        
        public CurrentOilPriceProvincialResponseBody(string CurrentOilPriceProvincialResult)
        {
            this.CurrentOilPriceProvincialResult = CurrentOilPriceProvincialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOilPriceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOilPrice", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.GetOilPriceRequestBody Body;
        
        public GetOilPriceRequest()
        {
        }
        
        public GetOilPriceRequest(OilPrice.GetOilPriceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class GetOilPriceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Language;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short DD;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short MM;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public short YYYY;
        
        public GetOilPriceRequestBody()
        {
        }
        
        public GetOilPriceRequestBody(string Language, short DD, short MM, short YYYY)
        {
            this.Language = Language;
            this.DD = DD;
            this.MM = MM;
            this.YYYY = YYYY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOilPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOilPriceResponse", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.GetOilPriceResponseBody Body;
        
        public GetOilPriceResponse()
        {
        }
        
        public GetOilPriceResponse(OilPrice.GetOilPriceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class GetOilPriceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOilPriceResult;
        
        public GetOilPriceResponseBody()
        {
        }
        
        public GetOilPriceResponseBody(string GetOilPriceResult)
        {
            this.GetOilPriceResult = GetOilPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOilPriceProvincialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOilPriceProvincial", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.GetOilPriceProvincialRequestBody Body;
        
        public GetOilPriceProvincialRequest()
        {
        }
        
        public GetOilPriceProvincialRequest(OilPrice.GetOilPriceProvincialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class GetOilPriceProvincialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Language;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short DD;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short MM;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public short YYYY;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Province;
        
        public GetOilPriceProvincialRequestBody()
        {
        }
        
        public GetOilPriceProvincialRequestBody(string Language, short DD, short MM, short YYYY, string Province)
        {
            this.Language = Language;
            this.DD = DD;
            this.MM = MM;
            this.YYYY = YYYY;
            this.Province = Province;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOilPriceProvincialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOilPriceProvincialResponse", Namespace="http://www.pttor.com", Order=0)]
        public OilPrice.GetOilPriceProvincialResponseBody Body;
        
        public GetOilPriceProvincialResponse()
        {
        }
        
        public GetOilPriceProvincialResponse(OilPrice.GetOilPriceProvincialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.pttor.com")]
    public partial class GetOilPriceProvincialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOilPriceProvincialResult;
        
        public GetOilPriceProvincialResponseBody()
        {
        }
        
        public GetOilPriceProvincialResponseBody(string GetOilPriceProvincialResult)
        {
            this.GetOilPriceProvincialResult = GetOilPriceProvincialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OilPriceSoapChannel : OilPrice.OilPriceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OilPriceSoapClient : System.ServiceModel.ClientBase<OilPrice.OilPriceSoap>, OilPrice.OilPriceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OilPriceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OilPriceSoapClient.GetBindingForEndpoint(endpointConfiguration), OilPriceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OilPriceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OilPriceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OilPriceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OilPriceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OilPriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OilPrice.CurrentOilPriceResponse> OilPrice.OilPriceSoap.CurrentOilPriceAsync(OilPrice.CurrentOilPriceRequest request)
        {
            return base.Channel.CurrentOilPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<OilPrice.CurrentOilPriceResponse> CurrentOilPriceAsync(string Language)
        {
            OilPrice.CurrentOilPriceRequest inValue = new OilPrice.CurrentOilPriceRequest();
            inValue.Body = new OilPrice.CurrentOilPriceRequestBody();
            inValue.Body.Language = Language;
            return ((OilPrice.OilPriceSoap)(this)).CurrentOilPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OilPrice.CurrentOilPriceProvincialResponse> OilPrice.OilPriceSoap.CurrentOilPriceProvincialAsync(OilPrice.CurrentOilPriceProvincialRequest request)
        {
            return base.Channel.CurrentOilPriceProvincialAsync(request);
        }
        
        public System.Threading.Tasks.Task<OilPrice.CurrentOilPriceProvincialResponse> CurrentOilPriceProvincialAsync(string Language, string Province)
        {
            OilPrice.CurrentOilPriceProvincialRequest inValue = new OilPrice.CurrentOilPriceProvincialRequest();
            inValue.Body = new OilPrice.CurrentOilPriceProvincialRequestBody();
            inValue.Body.Language = Language;
            inValue.Body.Province = Province;
            return ((OilPrice.OilPriceSoap)(this)).CurrentOilPriceProvincialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OilPrice.GetOilPriceResponse> OilPrice.OilPriceSoap.GetOilPriceAsync(OilPrice.GetOilPriceRequest request)
        {
            return base.Channel.GetOilPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<OilPrice.GetOilPriceResponse> GetOilPriceAsync(string Language, short DD, short MM, short YYYY)
        {
            OilPrice.GetOilPriceRequest inValue = new OilPrice.GetOilPriceRequest();
            inValue.Body = new OilPrice.GetOilPriceRequestBody();
            inValue.Body.Language = Language;
            inValue.Body.DD = DD;
            inValue.Body.MM = MM;
            inValue.Body.YYYY = YYYY;
            return ((OilPrice.OilPriceSoap)(this)).GetOilPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OilPrice.GetOilPriceProvincialResponse> OilPrice.OilPriceSoap.GetOilPriceProvincialAsync(OilPrice.GetOilPriceProvincialRequest request)
        {
            return base.Channel.GetOilPriceProvincialAsync(request);
        }
        
        public System.Threading.Tasks.Task<OilPrice.GetOilPriceProvincialResponse> GetOilPriceProvincialAsync(string Language, short DD, short MM, short YYYY, string Province)
        {
            OilPrice.GetOilPriceProvincialRequest inValue = new OilPrice.GetOilPriceProvincialRequest();
            inValue.Body = new OilPrice.GetOilPriceProvincialRequestBody();
            inValue.Body.Language = Language;
            inValue.Body.DD = DD;
            inValue.Body.MM = MM;
            inValue.Body.YYYY = YYYY;
            inValue.Body.Province = Province;
            return ((OilPrice.OilPriceSoap)(this)).GetOilPriceProvincialAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OilPriceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OilPriceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OilPriceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www1.pttor.com/OilPrice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OilPriceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www1.pttor.com/OilPrice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OilPriceSoap,
            
            OilPriceSoap12,
        }
    }
}
